### ISSUE TITLE
Insufficient error handling when servers don't serve sane data

### ISSUE THREAD

**Issue by kav2k** [SeinopSys/Deviant-Notify#1]
When dA servers reply with a 500, that causes knock-on effects in the code:

* Server responds with status 500 and a HTML page with error.
* Error is reported at `request-utils.js:218`: `Failed to get message counts SyntaxError: Unexpected token < in JSON at position 0`
* Badge displays as `NaNn`
* Similar in the popup interface.
* A notification is fired as if new messages are there.

**Comment by SeinopSys** [comment]
Moved to https://github.com/DJDavid98/Deviant-Notify/issues/1
