### ISSUE TITLE
Filtering types of feedback notifications

### ISSUE THREAD

**Issue by Gecko998** [SeinopSys/Deviant-Notify#7]
My apologies if this was one of the already added improvements/issues, I wasn't really sure

I personally only would like to be notified if I get a comment/reply/mention/note etc. (Basically any feedback notification that isn't a favourite, watch or a llama badge as I get lots of those)
I didn't see a way to filter this so I was wondering if this was possible or not? 

Thanks!

**Comment by SeinopSys** [comment]
This is not yet possible, but it will be tracked under #5, please subscribe to that issue to be notified of updates
